# pull the htppd docker image
FROM httpd:latest

# person who is maintinag the docker file
MAINTAINER "bharath.ca58@gmail.com"

# copying the the petshop application file from the source directory to destincation HTTPD Container directory
COPY . /usr/local/apache2/htdocs/
